#!/bin/sh
# (c) Positive Technologies 2012
# Author: Timur Gilmullin
#
# Your must install Power Shell on Win. Then put this file into your .git/hooks/ directory.
#
# Setup path to commands for execute.
#
# Path to local PowerShell:
powerShell="c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy RemoteSigned -Command"
# Set your paths
pathToTest="path_to_tests.py"
pathToPython="path_to_python.exe"
# Command to run unittest:
testRun="$pathToPython $pathToTest"
# Running pre-commit and gets exit-code:
runString=$powerShell' '$testRun
exec $runString
exitCode=$?
echo "Exit-code of unittest is:"
echo $exitCode
if [ x"$exitCode" == x"0" ]
then
 exit 0
else
 echo "Not all unit-tests passed! Commit cancelled!"
 exit 1
fi